config/routes.rb
Vetshop::Application.routes.draw do
  resources :customers do
    resources :pets
  end

  resources :appointments

  resources :pets

  get "doctors/index"

 resources :doctors
 
 

end

app/models/pet.rb
class Pet < ActiveRecord::Base
has_many :appointments
belongs_to :customer
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  # GET /pets
  # GET /pets.xml
  def index
    @pets = Pet.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pets }
    end
  end

  # GET /pets/1
  # GET /pets/1.xml
  def show
    @pet = Pet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pet }
    end
  end

  # GET /pets/new
  # GET /pets/new.xml
  def new
    @pet = Pet.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pet }
    end
  end

  # GET /pets/1/edit
  def edit
    @pet = Pet.find(params[:id])
  end

  # POST /pets
  # POST /pets.xml
  def create
    
    @customer = Customer.find(params[:customer_id])
    @pet = @customer.pets.build(params[:pet])
    respond_to do |format|
      if @pet.save
        format.html { redirect_to(@pet, :notice => 'Pet was successfully created.') }
        format.xml  { render :xml => @pet, :status => :created, :location => @pet }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pets/1
  # PUT /pets/1.xml
  def update
    @pet = Pet.find(params[:id])

    respond_to do |format|
      if @pet.update_attributes(params[:pet])
        format.html { redirect_to(@pet, :notice => 'Pet was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.xml
  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to(pets_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_for [@customer,@pet], :url => customer_pets_path do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :breed %><br />
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :last_visit %><br />
    <%= f.date_select :last_visit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<h1>Listing pets</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Breed</th>
    <th>Age</th>
    <th>Weight</th>
    <th>Last visit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pets.each do |pet| %>
  <tr>
    <td><%= pet.name %></td>
    <td><%= pet.type %></td>
    <td><%= pet.breed %></td>
    <td><%= pet.age %></td>
    <td><%= pet.weight %></td>
    <td><%= pet.last_visit %></td>
    <td><%= link_to 'Show', pet %></td>
    <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
    <td><%= link_to 'Destroy', pet, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pet', new_customer_pet_path %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', new_customer_pet_path %>

app/views/pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @pet.name %>
</p>

<p>
  <b>Type:</b>
  <%= @pet.type %>
</p>

<p>
  <b>Breed:</b>
  <%= @pet.breed %>
</p>

<p>
  <b>Age:</b>
  <%= @pet.age %>
</p>

<p>
  <b>Weight:</b>
  <%= @pet.weight %>
</p>

<p>
  <b>Last visit:</b>
  <%= @pet.last_visit %>
</p>


<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', pets_path %>