config/routes.rb
Vetshop::Application.routes.draw do
  resources :customers do
    resources :pets
  end

  resources :appointments

  resources :pets

  get "doctors/index"

 resources :doctors
 
 

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
has_many :appointments

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def index
    @doctors = Doctor.all

    respond_to do |format|
      format.html # index.html.erb
    
    end
  end

  # GET /doctors/1
  # GET /doctors/1.xml
  def show
    @doctor = Doctor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @doctor }
    end
  end

  # GET /doctors/new
  # GET /doctors/new.xml
  def new
    @doctor = Doctor.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @doctor }
    end
  end

  # GET /doctors/1/edit
  def edit
    @doctor = Doctor.find(params[:id])
  end
  
 
 
  def create
    @doctor = Doctor.new(params[:doctor])

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to(@doctor, :notice => 'doctor was successfully created.') }
        format.xml  { render :xml => @doctor, :status => :created, :location => @doctor }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @doctor.errors, :status => :unprocessable_entity }
      end
    end
  end
  # PUT /doctors/1
   # PUT /doctors/1.xml
   def update
     @doctor = Doctor.find(params[:id])

     respond_to do |format|
       if @doctor.update_attributes(params[:doctor])
         format.html { redirect_to(@doctor, :notice => 'Doctor was successfully updated.') }
         format.xml  { head :ok }
       else
         format.html { render :action => "edit" }
         format.xml  { render :xml => @doctor.errors, :status => :unprocessable_entity }
       end
     end
   end

   # DELETE /doctors/1
   # DELETE /doctors/1.xml
   def destroy
     @doctor = Doctor.find(params[:id])
     @doctor.destroy

     respond_to do |format|
       format.html { redirect_to(doctors_url) }
       format.xml  { head :ok }
     end
   end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :school %><br />
    <%= f.text_field  :school %>
  </div>
  <div class="field">
    <%= f.label :years_in_practice %><br />
    <%= f.select :years_in_practice,options_for_select(1..100) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<h1>Listing Doctors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>School</th>
    <th>Years in Practice</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @doctors.each do |doctor| %>
  <tr>
    <td><%= doctor.name %></td>
    <td><%= doctor.address %></td>
    <td><%= doctor.city %></td>
    <td><%= doctor.state %></td>
    <td><%= doctor.school %></td>
    <td><%= doctor.years_in_practice %></td>
    <td><%= link_to 'Show', doctor %></td>
    <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
    <td><%= link_to 'Destroy', doctor, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />


<p><%= link_to "Add Doctor", new_doctor_path %></p>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @doctor.name %>
</p>

<p>
  <b>Address:</b>
  <%= @doctor.address %>
</p>

<p>
  <b>City:</b>
  <%= @doctor.city%>
</p>

<p>
  <b>State:</b>
  <%= @doctor.state%>
</p>

<p>
  <b>Zip:</b>
  <%= @doctor.zip %>
</p>

<p>
  <b>School:</b>
  <%= @doctor.school %>
</p>
<p>
  <b>Years in Practice:</b>
  <%= @doctor.years_in_practice %>
</p>



<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>